//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiiExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiiExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JSystem audio archive used for storing a select few files
        ///
        ///Supported games include:
        ///- Super Mario Galaxy
        ///- Super Mario Galaxy 2.
        /// </summary>
        internal static string ArchiveFormat_JSystemAAF_Description {
            get {
                return ResourceManager.GetString("ArchiveFormat_JSystemAAF_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSystem AAF.
        /// </summary>
        internal static string ArchiveFormat_JSystemAAF_Name {
            get {
                return ResourceManager.GetString("ArchiveFormat_JSystemAAF_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive format used in JSystem
        ///
        ///Supported games include:
        ///- Pikmin
        ///- Luigi&apos;s Mansion
        ///- Super Mario Sunshine
        ///- The Legend of Zelda:
        ///    The Wind Waker
        ///- Mario Kart: Double Dash!!
        ///- Donkey Kong Jungle Beat
        ///- The Legend of Zelda:
        ///    Twilight Princess
        ///- Super Mario Galaxy
        ///- Super Mario Galaxy 2.
        /// </summary>
        internal static string ArchiveFormat_JSystemRARC_Description {
            get {
                return ResourceManager.GetString("ArchiveFormat_JSystemRARC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSystem Archive.
        /// </summary>
        internal static string ArchiveFormat_JSystemRARC_Name {
            get {
                return ResourceManager.GetString("ArchiveFormat_JSystemRARC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive format used in NW4R
        ///
        ///Supported games include:
        ///- Super Paper Mario
        ///- Mario Kart Wii
        ///- Metroid: Other M
        ///- Sonic Colors [Wii]
        ///- Mario and Sonic at the
        ///    London 2012 Olympic Games
        ///- The Legend of Zelda:
        ///    Skyward Sword
        ///- Rodea the Sky Soldier.
        /// </summary>
        internal static string ArchiveFormat_NW4RArchive_Description {
            get {
                return ResourceManager.GetString("ArchiveFormat_NW4RArchive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW4R Archive.
        /// </summary>
        internal static string ArchiveFormat_NW4RArchive_Name {
            get {
                return ResourceManager.GetString("ArchiveFormat_NW4RArchive_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string CompressionName_Off {
            get {
                return ResourceManager.GetString("CompressionName_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay0 Strong.
        /// </summary>
        internal static string CompressionName_YAY0Strong {
            get {
                return ResourceManager.GetString("CompressionName_YAY0Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaz0 Fast.
        /// </summary>
        internal static string CompressionName_YAZ0Fast {
            get {
                return ResourceManager.GetString("CompressionName_YAZ0Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaz0 Official.
        /// </summary>
        internal static string CompressionName_YAZ0Official {
            get {
                return ResourceManager.GetString("CompressionName_YAZ0Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaz0 Strong.
        /// </summary>
        internal static string CompressionName_YAZ0Strong {
            get {
                return ResourceManager.GetString("CompressionName_YAZ0Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files|*.*.
        /// </summary>
        internal static string FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Files|*.arc;*.szs;*.szp;*.carc;*.app;*.aaf|Resource Archive|*.arc|YAZ0 Identified Archive|*.szs|YAY0 Identified Archive|*.szp|U8 Archive|*.szs;*.carc;*.app|Audio Archive File|*.szs;*.aaf|All Files|*.*.
        /// </summary>
        internal static string FileFilter_SupportedArchives {
            get {
                return ResourceManager.GetString("FileFilter_SupportedArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process exited with code {0}.
        /// </summary>
        internal static string InvalidOperationException_ProcessExitedWithCode {
            get {
                return ResourceManager.GetString("InvalidOperationException_ProcessExitedWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the archive as {0}:
        ///{1}
        ///
        ///{2}.
        /// </summary>
        internal static string MessageBoxMsg_ArchiveFormatReadError {
            get {
                return ResourceManager.GetString("MessageBoxMsg_ArchiveFormatReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Compresion?.
        /// </summary>
        internal static string MessageBoxMsg_CancelCompression {
            get {
                return ResourceManager.GetString("MessageBoxMsg_CancelCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are trying to drag an item onto your desktop,
        ///use the Right Mouse Button to do so..
        /// </summary>
        internal static string MessageBoxMsg_DragDropUseRightClickHint {
            get {
                return ResourceManager.GetString("MessageBoxMsg_DragDropUseRightClickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory already exists!
        ///&quot;{0}&quot;
        ///Some of the contents may be overwritten.
        ///
        ///Proceed?.
        /// </summary>
        internal static string MessageBoxMsg_ExportDirectoryOverwriteWarning {
            get {
                return ResourceManager.GetString("MessageBoxMsg_ExportDirectoryOverwriteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the name &quot;{0}&quot;
        ///already exists at &quot;{1}&quot;.
        /// </summary>
        internal static string MessageBoxMsg_ItemWithTheSameNameError {
            get {
                return ResourceManager.GetString("MessageBoxMsg_ItemWithTheSameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for WiiExplorer is available. To continue using WiiExplorer, please update to the latest version.
        ///
        ///{0}
        ///
        ///{1}.
        /// </summary>
        internal static string MessageBoxMsg_MandatoryUpdateNotice {
            get {
                return ResourceManager.GetString("MessageBoxMsg_MandatoryUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you tried to open is not supported..
        /// </summary>
        internal static string MessageBoxMsg_NotSupportedArchiveFormat {
            get {
                return ResourceManager.GetString("MessageBoxMsg_NotSupportedArchiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for WiiExplorer is available!
        ///
        ///{0}
        ///
        ///{1}.
        /// </summary>
        internal static string MessageBoxMsg_OptionalUpdateNotice {
            get {
                return ResourceManager.GetString("MessageBoxMsg_OptionalUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen encoding type doesn&apos;t match the file extension.
        ///SZP files are supposed to be YAY0 Encoded, would you like to switch to YAY0 Strong?.
        /// </summary>
        internal static string MessageBoxMsg_SZPMismatch {
            get {
                return ResourceManager.GetString("MessageBoxMsg_SZPMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen encoding type doesn&apos;t match the file extension.
        ///SZS files are supposed to be YAZ0 Encoded, would you like to switch to YAZ0 Strong?.
        /// </summary>
        internal static string MessageBoxMsg_SZSMismatch {
            get {
                return ResourceManager.GetString("MessageBoxMsg_SZSMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, are you sure you want to proceed?.
        /// </summary>
        internal static string MessageBoxMsg_UnsavedChangesNotice {
            get {
                return ResourceManager.GetString("MessageBoxMsg_UnsavedChangesNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured trying to execute the following command:\n\n{0}\n\n{1}.
        /// </summary>
        internal static string MessageBoxMsg_UserCompressionExecuteFailure {
            get {
                return ResourceManager.GetString("MessageBoxMsg_UserCompressionExecuteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured trying to parse the following command:\n\n{0}\n\n{1}.
        /// </summary>
        internal static string MessageBoxMsg_UserCompressionParseFailure {
            get {
                return ResourceManager.GetString("MessageBoxMsg_UserCompressionParseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive read error.
        /// </summary>
        internal static string MessageBoxTitle_ArchiveReadError {
            get {
                return ResourceManager.GetString("MessageBoxTitle_ArchiveReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Action.
        /// </summary>
        internal static string MessageBoxTitle_ConfirmAction {
            get {
                return ResourceManager.GetString("MessageBoxTitle_ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Mismatch.
        /// </summary>
        internal static string MessageBoxTitle_EncodingMismatch {
            get {
                return ResourceManager.GetString("MessageBoxTitle_EncodingMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageBoxTitle_Information {
            get {
                return ResourceManager.GetString("MessageBoxTitle_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name Conflict.
        /// </summary>
        internal static string MessageBoxTitle_ItemNameConflict {
            get {
                return ResourceManager.GetString("MessageBoxTitle_ItemNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string MessageBoxTitle_UpdateAvailable {
            get {
                return ResourceManager.GetString("MessageBoxTitle_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Required.
        /// </summary>
        internal static string MessageBoxTitle_UpdateRequired {
            get {
                return ResourceManager.GetString("MessageBoxTitle_UpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Compression Execute Error.
        /// </summary>
        internal static string MessageBoxTitle_UserCompressionExecuteError {
            get {
                return ResourceManager.GetString("MessageBoxTitle_UserCompressionExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MessageBoxTitle_Warning {
            get {
                return ResourceManager.GetString("MessageBoxTitle_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive loaded successfully! [{0} file(s) total].
        /// </summary>
        internal static string StatusStrip_ArchiveLoadedSuccessfully {
            get {
                return ResourceManager.GetString("StatusStrip_ArchiveLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Cancelled. (Saved without compression.).
        /// </summary>
        internal static string StatusStrip_CompressionCancelled {
            get {
                return ResourceManager.GetString("StatusStrip_CompressionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Compressing: {1}%.
        /// </summary>
        internal static string StatusStrip_InProgressCompression {
            get {
                return ResourceManager.GetString("StatusStrip_InProgressCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection.
        /// </summary>
        internal static string StatusStrip_NoSelection {
            get {
                return ResourceManager.GetString("StatusStrip_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        internal static string StatusStrip_RenamedItem {
            get {
                return ResourceManager.GetString("StatusStrip_RenamedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Complete!.
        /// </summary>
        internal static string StatusStrip_SaveComplete {
            get {
                return ResourceManager.GetString("StatusStrip_SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Complete! [{0}% ratio in {1}].
        /// </summary>
        internal static string StatusStrip_SaveCompleteCompression {
            get {
                return ResourceManager.GetString("StatusStrip_SaveCompleteCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} bytes. [CRC: {2}].
        /// </summary>
        internal static string StatusStrip_SelectedFileStats {
            get {
                return ResourceManager.GetString("StatusStrip_SelectedFileStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} files, {2} subfolders.
        /// </summary>
        internal static string StatusStrip_SelectedFolderStats {
            get {
                return ResourceManager.GetString("StatusStrip_SelectedFolderStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Archive Format on the left..
        /// </summary>
        internal static string String_NewArchiveGuide {
            get {
                return ResourceManager.GetString("String_NewArchiveGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewArchive.
        /// </summary>
        internal static string String_NewArchiveRootName {
            get {
                return ResourceManager.GetString("String_NewArchiveRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release information.
        /// </summary>
        internal static string String_ReleaseInformation {
            get {
                return ResourceManager.GetString("String_ReleaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string String_Version {
            get {
                return ResourceManager.GetString("String_Version", resourceCulture);
            }
        }
    }
}
