//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiiExplorer.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiiExplorer.Properties.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} File(s) added..
        /// </summary>
        internal static string AddedFilesMessage {
            get {
                return ResourceManager.GetString("AddedFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder added..
        /// </summary>
        internal static string AddedNewFolderMessage {
            get {
                return ResourceManager.GetString("AddedNewFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive loaded successfully! ({0} File(s) total).
        /// </summary>
        internal static string ArchiveLoadedMessage {
            get {
                return ResourceManager.GetString("ArchiveLoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory already exists.
        ///Are you sure you want to replace it?.
        /// </summary>
        internal static string DirectoryExists {
            get {
                return ResourceManager.GetString("DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Name.
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} encoding, please wait. {1} Elapsed, {2} Estimated).
        /// </summary>
        internal static string EncodingMessage {
            get {
                return ResourceManager.GetString("EncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Mismatch.
        /// </summary>
        internal static string EncodingMismatch {
            get {
                return ResourceManager.GetString("EncodingMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Archive &quot;{0}&quot; has been saved!.
        /// </summary>
        internal static string ExportAllMessage {
            get {
                return ResourceManager.GetString("ExportAllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; ({1} Bytes).
        /// </summary>
        internal static string FileClick {
            get {
                return ResourceManager.GetString("FileClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; ({1} Item(s)).
        /// </summary>
        internal static string FolderClick {
            get {
                return ResourceManager.GetString("FolderClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; Imported..
        /// </summary>
        internal static string ImportedFolderMessage {
            get {
                return ResourceManager.GetString("ImportedFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an item with this name in this directory.
        /// </summary>
        internal static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of &quot;{0}&quot; have been updated..
        /// </summary>
        internal static string ItemPropertyUpdateMessage {
            get {
                return ResourceManager.GetString("ItemPropertyUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been saved!.
        /// </summary>
        internal static string ItemSavedMessage {
            get {
                return ResourceManager.GetString("ItemSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Archive.
        /// </summary>
        internal static string NewArchive {
            get {
                return ResourceManager.GetString("NewArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a new archive from &quot;{0}&quot;.
        /// </summary>
        internal static string NewArchiveFromMessage {
            get {
                return ResourceManager.GetString("NewArchiveFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a new archive..
        /// </summary>
        internal static string NewArchiveMessage {
            get {
                return ResourceManager.GetString("NewArchiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Files|*.arc;*.szs;*.szp|Revolution Archives|*.arc|YAZ0 Identified Revolution Archives|*.szs|YAY0 Identified Revolution Archives|*.szp|All Files|*.*.
        /// </summary>
        internal static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been removed..
        /// </summary>
        internal static string RemoveItemMessage {
            get {
                return ResourceManager.GetString("RemoveItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been renamed to &quot;{1}&quot;..
        /// </summary>
        internal static string RenameItemMessage {
            get {
                return ResourceManager.GetString("RenameItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiiExplorer - Rename &quot;{0}&quot;.
        /// </summary>
        internal static string RenameWindowTitle {
            get {
                return ResourceManager.GetString("RenameWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has replaced &quot;{1}&quot;!.
        /// </summary>
        internal static string ReplaceItemMessage {
            get {
                return ResourceManager.GetString("ReplaceItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive saved successfully!{0}.
        /// </summary>
        internal static string SaveCompleteMessage {
            get {
                return ResourceManager.GetString("SaveCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen encoding type doesn&apos;t match the file extension.
        ///SZP files are supposed to be YAY0 Encoded, would you like to switch to YAY0 Strong?.
        /// </summary>
        internal static string SZPMismatch {
            get {
                return ResourceManager.GetString("SZPMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen encoding type doesn&apos;t match the file extension.
        ///SZS files are supposed to be YAZ0 Encoded, would you like to switch to YAZ0 Strong?.
        /// </summary>
        internal static string SZSMismatch {
            get {
                return ResourceManager.GetString("SZSMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.
        ///Are you sure you want to start a new file?.
        /// </summary>
        internal static string UnsavedChangesNewFile {
            get {
                return ResourceManager.GetString("UnsavedChangesNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.
        ///Are you sure you want to quit?.
        /// </summary>
        internal static string UnsavedChangesOnQuit {
            get {
                return ResourceManager.GetString("UnsavedChangesOnQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.
        ///Are you sure you want to open another file?.
        /// </summary>
        internal static string UnsavedChangesOpenFile {
            get {
                return ResourceManager.GetString("UnsavedChangesOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
